services:
  storage-node-2:
    build: ./storage-node-2
    container_name: distridoc-node-2
    ports:
      - "5002:5002"
    env_file:
      - .env.node2
    volumes:
      - node2-uploads:/app/uploads

volumes:
  node2-uploads:
