services:

  gateway-server:
    build: ./gateway-server
    container_name: distridoc-gateway
    ports:
      - "5000:5000"

    environment:
      - PORT=5000
      - JWT_EXPIRE=7d
      - MONGO_URI=mongodb+srv://sakshyamkataria:Sakshyam123!@cluster0.utwe9.mongodb.net/student-doc-repo
      - REDIS_URL=redis://default:or7PqyAgKlf30MMIAi8TeYa7eeEnITLu@fact-coherent-champagne-12103.db.redis.io:11543
      - JWT_SECRET=supersecretjwtkey_override_in_prod
      - STORAGE_NODE_1=http://storage-node-1:5001
      - STORAGE_NODE_2=http://storage-node-2:5002
      - CORS_ORIGIN=*
      - SERVICE_SECRET=distridoc-internal-secret-2026

    networks:
      - distridoc-net

  storage-node-1:
    build: ./storage-node-1
    container_name: distridoc-node-1

    ports:
      - "5001:5001"

    environment:
      - PORT=5001
      - NODE_ID=storage-node-1
      - MONGO_URI=mongodb+srv://sakshyamkataria:Sakshyam123!@cluster0.utwe9.mongodb.net/storage-node-1-db
      - REDIS_URL=redis://default:or7PqyAgKlf30MMIAi8TeYa7eeEnITLu@fact-coherent-champagne-12103.db.redis.io:11543
      - GATEWAY_URL=http://gateway-server:5000
      - PEER_NODE_URL=http://storage-node-2:5002
      - PEER_NODE_ID=storage-node-2
      - SELF_URL=http://storage-node-1:5001
      - SERVICE_SECRET=distridoc-internal-secret-2026

    volumes:
      - node1-uploads:/app/uploads

    networks:
      - distridoc-net

  storage-node-2:
    build: ./storage-node-2
    container_name: distridoc-node-2

    ports:
      - "5002:5002"

    environment:
      - PORT=5002
      - NODE_ID=storage-node-2
      - MONGO_URI=mongodb+srv://sakshyamkataria:Sakshyam123!@cluster0.utwe9.mongodb.net/storage-node-2-db
      - REDIS_URL=redis://default:or7PqyAgKlf30MMIAi8TeYa7eeEnITLu@fact-coherent-champagne-12103.db.redis.io:11543
      - GATEWAY_URL=http://gateway-server:5000
      - PEER_NODE_URL=http://storage-node-1:5001
      - PEER_NODE_ID=storage-node-1
      - SELF_URL=http://storage-node-2:5002
      - SERVICE_SECRET=distridoc-internal-secret-2026

    volumes:
      - node2-uploads:/app/uploads

    networks:
      - distridoc-net

  frontend:
    build:
      context: ./frontend
      args:
        - VITE_API_URL=http://localhost:5000/api
        - VITE_SOCKET_URL=http://localhost:5000

    container_name: distridoc-frontend

    ports:
      - "3000:80"

    depends_on:
      - gateway-server

    networks:
      - distridoc-net

networks:
  distridoc-net:
    driver: bridge

volumes:
  node1-uploads:
  node2-uploads: